# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#source: source
safe: true

destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

gems:
  - jekyll-redirect-from
  - jekyll-paginate

whitelist:
  - jekyll-redirect-from
  - jekyll-paginate

paginate: 20
paginate_path: /blog/:num/

# permalink and highlighter
permalink   : /:year/:month/:title.html
markdown    : kramdown
highlighter : rouge

gist:
   noscript: false

kramdown:
   input: GFM
   hard_wrap: false
   math_engine: mathjax

# SEO settings
title: Richard Banks
description: ""
keywords: "blog, agile, .net, architecture, software development, design, scrum"

# Site settings
url: https://www.richard-banks.org
enforce_ssl: www.richard-banks.org
baseurl: ""

# Author settings
author:
  name      : Richard Banks
  job       : 
  bio       : ".NET Developer, Scrum Coach and Trainer, Architect, Speaker, Author, and more"
  thumb     : /images/author.jpg
  email     : rbanks54@gmail.com
  url       : http://richard-banks.org
  github    : http://github.com/rbanks54
  twitter   : http://twitter.com/rbanks54
  facebook  : http://facebook.com/rbanks54
  linkedin  : http://lnkd.in/fW43nT
  gplus     : http://profiles.google.com/rbanks54?rel=author
  youtube   : https://www.youtube.com/channel/UCH2GpKQnz8io_fM7JRZFR2g
  vimeo     : https://vimeo.com/user31588688
  stackexchange : http://stackexchange.com/users/24761

google_analytics: UA-1055163-1
repo: http://github.com/rbanks54

# comments
disqus_shortname: ""
